env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - prettier
parserOptions:
  ecmaVersion: latest
rules:
  max-len: off
  no-unused-vars: off
  require-jsdoc: off
  no-throw-literal: off