version: '3.4'

services:
  hardhatproject:
    image: hardhatproject
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8008:8008