version: "3"

services:
  eth-node:
    image: "us-docker.pkg.dev/covalent-project/network/cqt-staking:latest-refiner-test"
    container_name: hardhat-node
    restart: on-failure
    expose:
      - 8545:8545
    entrypoint: |
      /bin/bash -l -c "
        echo "hardhat-node-address:" $NODE_ETHEREUM_MAINNET 
        echo "forked-node-address:" $ERIGON_NODE
        ./entrypoint.sh;"
    networks:
      - cqt-net
    environment:
      - ERIGON_NODE=${ERIGON_NODE}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - "8545:8545"

  cqt-staking:
    image: "us-docker.pkg.dev/covalent-project/network/cqt-staking:latest-refiner-test"
    container_name: proof-chain
    restart: on-failure
    entrypoint: |
      /bin/bash -l -c "
        echo Waiting for hardhat node to start up...;
        sleep 20;
        echo hard-hat node started!;
        echo $ERIGON_NODE "forked-node"
        npm run docker:deploy;
        sleep 1000000"
    depends_on:
      - eth-node
    networks:
      - cqt-net
    ports:
      - "8008:8008"

networks:
  cqt-net:
